version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/Floney-Server
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: script/stop.sh
      timeout: 60
      runsas: ubuntu
  ApplicationStart:
    - location: script/start.sh
      timeout: 60
      runsas: ubuntu
