version: 0.0
os: linux

files:
  - source: /
    destination: ~/Floney-Server
    overwrite: yes

file_exists_behavior: OVERWRITE

permissions:
  - object: /
    pattern: "**"
    owner: root
    group: root
    mode: 777

hooks:
  AfterInstall:
    - location: script/stop.sh
      timeout: 60
      runsas: root
  ApplicationStart:
    - location: script/start.sh
      timeout: 60
      runsas: root
